from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html', {'current_page': 'index'})


def table(request):
    items = [
        'Arcane Staff',
        'Armor of Valor',
        'Assassin Hood',
        'Assassin Jacket',
        'Assassin Shoes',
        'Astral Aegis',
        'Avalonian Axe',
        'Avalonian Demolition Hammer',
        'Avalonian Fishing Rod',
        'Avalonian Pickaxe',
        'Avalonian Sickle',
        'Avalonian Skinning Knife',
        'Avalonian Stone Hammer',
        'Axe',
        'Bag',
        'Battle Bracers',
        'Battleaxe',
        'Bear Paws',
        'Bedrock Mace',
        'Black Monk Stave',
        'Blazing Staff',
        'Blight Staff',
        'Bloodletter',
        'Bloodmoon Staff',
        'Boltcasters',
        'Boots of Valor',
        'Bow',
        'Bow of Badon',
        'Brawler Gloves',
        'Bridled Fury',
        'Brimstone Staff',
        'Broadsword',
        'Caitiff Shield',
        'Camlann Mace',
        'Cape',
        'Carrioncaller',
        'Carving Sword',
        'Celestial Censer',
        'Chillhowl',
        'Clarent Blade',
        'Claws',
        'Claymore',
        'Cleric Cowl',
        'Cleric Robe',
        'Cleric Sandals',
        'Cowl of Purity',
        'Crossbow',
        'Cryptcandle',
        'Cultist Cowl',
        'Cultist Robe',
        'Cultist Sandals',
        'Cursed Skull',
        'Cursed Staff',
        'Dagger',
        'Dagger Pair',
        'Damnation Staff',
        'Dawnsong',
        'Daybreaker',
        'Deathgivers',
        'Demolition Hammer',
        'Demon Armor',
        'Demon Boots',
        'Demon Helmet',
        'Demonfang',
        'Demonic Staff',
        'Divine Staff',
        'Double Bladed Staff',
        'Druid Cowl',
        'Druid Robe',
        'Druid Sandals',
        'Druidic Staff',
        'Dual Swords',
        'Duskweaver Armor',
        'Duskweaver Boots',
        'Duskweaver Helmet',
        'Earthrune Staff',
        'Energy Shaper',
        'Enigmatic Staff',
        'Evensong',
        'Eye of Secrets',
        'Facebreaker',
        'Fallen Staff',
        'Feyscale Hat',
        'Feyscale Robe',
        'Feyscale Sandals',
        'Fiend Cowl',
        'Fiend Robe',
        'Fiend Sandals',
        'Fire Staff',
        'Fisherman Backpack',
        'Fisherman Cap',
        'Fisherman Garb',
        'Fisherman Workboots',
        'Fishing Rod',
        'Fists of Avalon',
        'Forge Hammers',
        'Frost Staff',
        'Galatine Pair',
        'Glacial Staff',
        'Glaive',
        'Grailseeker',
        'Graveguard Armor',
        'Graveguard Boots',
        'Graveguard Helmet',
        'Great Arcane Staff',
        'Great Cursed Staff',
        'Great Fire Staff',
        'Great Frost Staff',
        'Great Hammer',
        'Great Holy Staff',
        'Great Nature Staff',
        'Greataxe',
        'Grovekeeper',
        'Guardian Armor',
        'Guardian Boots',
        'Guardian Helmet',
        'Halberd',
        'Hallowfall',
        'Hammer',
        'Hand of Justice',
        'Harvester Backpack',
        'Harvester Cap',
        'Harvester Garb',
        'Harvester Workboots',
        'Heavy Crossbow',
        'Heavy Mace',
        'Hellfire Hands',
        'Hellion Hood',
        'Hellion Jacket',
        'Hellion Shoes',
        'Hellspawn Staff',
        'Helmet of Valor',
        'Heron Spear',
        'Hoarfrost Staff',
        'Holy Staff',
        'Hood of Tenacity',
        'Hunter Hood',
        'Hunter Jacket',
        'Hunter Shoes',
        'Icicle Staff',
        'Incubus Mace',
        'Infernal Scythe',
        'Infernal Staff',
        'Iron-clad Staff',
        'Ironroot Staff',
        'Jacket of Tenacity',
        'Judicator Armor',
        'Judicator Boots',
        'Judicator Helmet',
        'Kingmaker',
        'Knight Armor',
        'Knight Boots',
        'Knight Helmet',
        'Leering Cane',
        'Lifecurse Staff',
        'Lifetouch Staff',
        'Lightcaller',
        'Light Crossbow',
        'Longbow',
        'Lumberjack Backpack',
        'Lumberjack Cap',
        'Lumberjack Garb',
        'Lumberjack Workboots',
        'Mace',
        'Mage Cowl',
        'Mage Robe',
        'Mage Sandals',
        'Malevolent Locus',
        'Mercenary Hood',
        'Mercenary Jacket',
        'Mercenary Shoes',
        'Miner Backpack',
        'Miner Cap',
        'Miner Garb',
        'Miner Workboots',
        'Mistcaller',
        'Mistpiercer',
        'Mistwalker Hood',
        'Mistwalker Jacket',
        'Mistwalker Shoes',
        'Morning Star',
        'Muisak',
        'Nature Staff',
        'Oathkeepers',
        'Occult Staff',
        'Permafrost Prism',
        'Pickaxe',
        'Pike',
        'Polehammer',
        'Primal Staff',
        'Prowling Staff',
        'Quarrier Backpack',
        'Quarrier Cap',
        'Quarrier Garb',
        'Quarrier Workboots',
        'Quarterstaff',
        'Rampant Staff',
        'Ravenstrike Cestus',
        'Realmbreaker',
        'Redemption Staff',
        'Robe of Purity',
        'Rootbound Staff',
        'Sacred Scepter',
        'Sandals of Purity',
        'Sarcophagus',
        'Satchel of Insight',
        'Scholar Cowl',
        'Scholar Robe',
        'Scholar Sandals',
        'Shadowcaller',
        'Shield',
        'Shoes of Tenacity',
        'Sickle',
        'Siegebow',
        'Skinner Backpack',
        'Skinner Cap',
        'Skinner Garb',
        'Skinner Workboots',
        'Skinning Knife',
        'Soldier Armor',
        'Soldier Boots',
        'Soldier Helmet',
        'Soulscythe',
        'Spear',
        'Specter Hood',
        'Specter Jacket',
        'Specter Shoes',
        'Spiked Gauntlets',
        'Spirithunter',
        'Staff of Balance',
        'Stalker Hood',
        'Stalker Jacket',
        'Stalker Shoes',
        'Stone Hammer',
        'Taproot',
        'Tombhammer',
        'Tome of Spells',
        'Torch',
        'Tracking Toolkit',
        'Trinity Spear',
        'Ursine Maulers',
        'Wailing Bow',
        'Warbow',
        'Weeping Repeater',
        'Whispering Bow',
        'Wild Staff',
        'Wildfire Staff',
        'Witchwork Staff'
    ]
    return render(request, 'table.html', {'current_page': 'table', 'items': items})

def tutorial(request):
    return render(request, 'tutorial.html', {'current_page': 'tutorial'})